theme: jekyll-theme-minimal
title: Understanding time in text
description: [Project goals: The Cognitive Computation Group aims to formulate machine learning tasks that will facilitate temporal reasoning in NLP.]
logo: CCG.png
